### ISSUE TITLE
Detect Ctrl+Click only on mouse-down (not on mouse-up)

### ISSUE THREAD

**Issue by N4rk0** [Microsoft/VS-PPT#54] opened 2016-08-25 21:58 UTC
When for exaple i do a control+c i often find myself doing this sequence:
left mouse down
control down
c down 
c up 
left mouse up -> here the goto definition gets triggered 
control up

This happens very often...would it be possible to disable the trigger on mouse up ?

**Comment by gix** [comment] 2016-09-30 15:15
Duplicate of https://github.com/Microsoft/VS-PPT/issues/25

**Comment by aamcampbell** [comment] 2016-12-01 22:56
Simple issue, but significantly annoying to multiple users.

**Comment by justcla** [comment] 2016-12-01 23:02
N4rk0, out of interest, why would you do that sequence?
I.e. what is the user scenario?

Something to do with copying the selected text, while still increasing the selection?
...and then an accidental timing/race-condition when releasing the keys. ?
Can you help me understand who a user would follow this sequence?

Thanks

**Comment by aamcampbell** [comment] 2016-12-01 23:18
Since I'm here, even though I'm not N4rk0...

Yes, it's a "race condition." Optimized programmers "multitask" by beginning mouse selections before releasing the CTRL key on a CTRL+c sequence. We don't place a mutex between the left hand (keyboard) and the right hand (mouse in this case) except where totally necessary.

For me personally, I actually do this more often with CTRL+V than CTRL+C. This usually happens because I paste in the text and instantly click it to start editing. Sometimes I think I actually click before releasing the "V", causing my text to paste into whatever file GoToDefinition took me to, and sometimes I'll then hit ESC so fast that I didn't notice that I just edited and broke some other file that I didn't want to touch. :P

The correct behavior of CTRL+Click would only fire GoToDefinition if CTRL were held down on both mouse down and mouse up. This would prevent unexpected interruptions like described here.

**Comment by justcla** [comment] 2016-12-01 23:21
Thanks

**Comment by justcla** [comment] 2016-12-01 23:26
That does sound like a problem. Naturally, all sorts of things can go wrong when the left and right hand don't work in sync. ;-)
But what you've described is not what N4rk0 described.
In his scenario, he starts clicking first, and then instigates a copy (while holding the mouse down), then ends both the copy and the mouse selection. I understand ending them both at the same time. But i don't understand holding down the mouse while doing to copy - unless you intend to continue to grow the selection after the copy, in which case, you wouldn't release the mouse before the Ctrl key.
So there must be some user error involved, which can happen. But still... why keep holding the mouse while making a copy?

**Comment by justcla** [comment] 2016-12-01 23:31
Two suggestions have been proposed now:
- activate GoToDef on mouse-down event
- activate GoToDef after "click" event (both mouse down mouse up) with Control having been held (on the same point?) for both operations

I think to avoid accidental race conditions when releasing both Ctrl and mouse at the same time, it would be best to implement GoToDef on mouse-down event.
What do you think?

**Comment by aamcampbell** [comment] 2016-12-01 23:40
Ok--sorry to misunderstand that. But I have done the same thing as well while making a copy. I just hit CTRL+C as soon as the mouse reaches the right character without thinking about whether the mouse click is lifted before or after CTRL+C is hit.

However, I will duly note that I tested this on VS2013 Pro with PPT installed, and GoToDef was _not_ invoked on MouseUp. So I'm actually unable to reproduce N4rk0's issue, unless it was introduced in a more recent PPT release.

But to answer your question: I definitely advocate GoToDef after a full "click" event (as does issue #25). Some users may hold CTRL while selecting text (to select by words), so GoToDef on mouse-down would break some workflows.

**Comment by justcla** [comment] 2016-12-01 23:52
>> Some users may hold CTRL while selecting text (to select by words)

Holding control only selects words when used with the arrow keys. Not the mouse.

The whole point of the feature is that if the user is holding the Ctrl key, then mouse hover will present a hyperlink, and mouse click will GoTo whatever is being pointed at.
So if the user holds Ctrl and clicks....they'd better watch out - because this feature is designed to have them navigate. :-D

**Comment by justcla** [comment] 2016-12-01 23:53
I can't think of any valid scenario where we would want to wait for the mouse-up event to occur.
Are there any?

**Comment by justcla** [comment] 2016-12-01 23:57
> However, I will duly note that I tested this on VS2013 Pro with PPT installed, and GoToDef was not invoked on MouseUp. So I'm actually unable to reproduce N4rk0's issue, unless it was introduced in a more recent PPT release.

N4rk0, what versions of Visual Studio and PPT are you using?

**Comment by aamcampbell** [comment] 2016-12-01 23:58
In my VS2013, CTRL does indeed cause the mouse to select one word at a time as well as the keyboard.

**Comment by justcla** [comment] 2016-12-02 00:05
Oh. I see that now. That's pretty tricky. ;-)
If you hold the Ctrl key before clicking, whole words get selected as you move your mouse.

That most certainly does cause a conflict.

It's very hard to support both features nicely.
And harder still if we're also trying to account for user accidents.

**Comment by justcla** [comment] 2016-12-02 00:09
If a user did this to select several words, then we ought to determine that the mouse-down and mouse-up were on different points, and go nowhere.

But if the user dd this to select one word (very common scenario for people who use Ctrl+Click to select word), then how would we know if they wanted to select the word, or go to the defn?

There's our problem.

The cleanest thing to do would be to disable Ctrl+Click Select Word if Ctrl+Click GoToDefn was installed. And then we might as well trigger it on mouse down.

**Comment by aamcampbell** [comment] 2016-12-02 00:15
Bit more feedback: don't bother disabling "Ctrl+Click Select Word" unless it interferes. I find it sensible to have the symbol selected when GoToDef is invoked. Not that it matters either way, but it's preferable not to change things that work fine.

**Comment by gix** [comment] 2016-12-02 06:19
I'd prefer to keep it firing on click as opposed to on mouse down. I think the only thing missing is to set a flag on mouse down if Ctrl is pressed and then check that flag in addition to all other flags in mouse up. Currently you can press the mouse down on an identifier (keep it pressed), then press Ctrl and the hyperlink shows up. That's not really a Ctrl-Click behavior.

The sequence the bug reporter describes seems to be the same as I described in #25:
Visual Studio supports copying the current line if nothing is selected. Normally you would:

  1. Mouse down somewhere in the line you want to copy. Possibly in the indentation whitespace.
  2. Mouse up at the same position.
  3. Push (and hold) Ctrl.
  4. Push C.
  5. Release C.
  6. Release Ctrl.

When doing this quickly it becomes:

  1. Mouse down somewhere in the line you want to copy. Possibly in the indentation whitespace.
  2. Push (and hold) Ctrl.
  3. Mouse up at the same position. -> GoToDef attempts to fire and shows error dialog.

Here the Ctrl was *not* pressed on the initial mouse down.

**Comment by N4rk0** [comment] 2016-12-02 11:49
Sorry for being so late... 
My problem is not when double click to select a word. 
It's related to the way i'm used to copy text.
The sequence that i perform is this:
1. Press Ctrl 
2. MouseDown somewere to start selecting
3. Select text
4/5.  These are almost simultaneous. Press C, MouseUp
6. Release Ctrl

At point 4/5 if the cursor is on top of a navigable word then it will fire the event.
A good solution that was proposed here was to check if the MouseDown and MouseUp were both performed on the same spot.

**Comment by justcla** [comment] 2016-12-02 16:22
Thanks for explaining the scenario. Now that I've discovered the power of holding control while selecting words, I can see how awesome it it. And your scenario makes sense.

The solution proposed - to check at mouse up whether the control key was held on the same item when the mouse was pressed down - is very technically challenging. As mentioned above we would need to store (somewhere) the state and position of every single mouse down action and then refer to it on every mouse up action. Apart from being challenging to implement, it could easily cause performance issues.
Life would be MUCH easier if we don't have to try to store the state and position of every mouse down event.
Hence, a solution that just works on mouse down is simple and effective - but would mean that selecting whole words with the control key would not work if and only if the first word selected was linkable.

That being said, the code is open-sourced. If somebody in the community feels they can implement the complicated "mouse click" solution properly (with good time/space performance) then we'd be happy to accept the pull request.

Thanks for the discussion guys!

**Comment by gix** [comment] 2016-12-03 15:21
The code already stores the position on every mouse down. How does setting an additional bool for the control key hurt there? (In fact, looking at the code, one could just skip caching the mouse position if control is not pressed.)

**Comment by justcla** [comment] 2016-12-03 21:00
That sounds pretty good!
Could you submit a pull request? I'll see if I can test it and get it pushed into the new version we're working on.

**Comment by N4rk0** [comment] 2017-03-02 18:58
I submitted a pull request.

**Comment by justcla** [comment] 2017-03-02 18:59
I just noticed. That's fantastic. Thanks.
I'm reviewing it now.

**Comment by justcla** [comment] 2017-03-03 06:37
Pull request has been tested and accepted.
Thanks to everyone for the great discussion.
And thanks to Francesco @N4rk0 for the pull request.

The fix has been released in v15.0.2. Download the latest version [here](https://marketplace.visualstudio.com/items?itemName=VisualStudioProductTeam.CtrlClickGoToDefinition).

**Closed by justcla** 2017-03-03 06:37 UTC

**Comment by N4rk0** [comment] 2017-03-03 11:49
I have visual studio 2015, how can i include this update in my working PPT version?

**Comment by justcla** [comment] 2017-03-03 17:18
One option is to upgrade to Visual Studio 2017, which will be officially launched on Tuesday.

Another options is to take the open source code and build it into a separate extension. Disable Ctrl+Click GoToDefn from PPT and install your own custom-built version of CC-GTD.

But otherwise, I'll need to build it into the VS2015 version, and release that one after testing.
I have another PPT-2015 change waiting to go out (with fix for exposing Custom Document Well commands for Window.GoToUnpinnedTab1..10). I'll hold that off and release the two fixes at the same time.

**Comment by N4rk0** [comment] 2017-03-05 12:00
I already used second option and it worked ok.
Thanks 👍
