### ISSUE TITLE
Editor Guidelines doesn't show in Editor context menu on 2017.RC2

### ISSUE THREAD

**Issue by PhilBarila** [Microsoft/VS-PPT#85] opened 2017-01-25 21:37 UTC
Not sure if it's my expectations or the extension.  Two installations showing identical behavior.  Can't tell that Editor Guidelines is installed, except that it shows up as Installed and Enabled in the Extensions and Updates dialog.  Perhaps the User is looking for evidence of function in the wrong place?  It's in the Editor context menu in 2013/15, so that's where I was expecting it.

Appreciate all the work on the extensions and Power Pack.

**Comment by justcla** [comment] 2017-01-25 23:43
Sorry. I'm confused by the wording in the post.
What's the issue?
What do you mean by "Two installations"?

" Perhaps the User is looking for evidence of function in the wrong place? "
What's that referring to?

**Comment by PhilBarila** [comment] 2017-01-26 00:04
You're right, that's really not clear at all.
Two machines with VS2017.RC2 installed.  Both exhibit the same behavior, which is no discernible behavior.  Has the UI to it changed from the Editor context menu to some place else?  Or is the absence of the context menu entry an indication it's not working correctly?

**Comment by Dany-R** [comment] 2017-01-26 17:14
Hi, I guess, that Phil does not find the context menu entries to set the guidelines, which happened to him on two installations (machines).

**Comment by diaphore** [comment] 2017-02-05 14:22
The context menu doesn't show up for me either (VS2017.RC3) and reading the comments on the [marketplace page](https://marketplace.visualstudio.com/items?itemName=VisualStudioProductTeam.EditorGuidelines) seems to indicate there's something wrong with this extensions.

**Comment by JVimes** [comment] 2017-02-09 17:01
2017 RC4, it still doesn't work. Or nobody can figure out how to turn it on.

**Comment by justcla** [comment] 2017-02-09 20:34
I have confirmed, this is not working in version 2.0

**Comment by tiesmaster** [comment] 2017-02-17 21:15
Same here, the menu entry is absent, though, it's actually in the context menu designer (see screenshot), so might be something wrong with the visibility, or "CanExecute" stuff.

![add-guideline-screenshot](https://cloud.githubusercontent.com/assets/460904/23083563/9a9ffe8a-f55e-11e6-8a98-9dd3b56bfb95.PNG)

**Comment by justcla** [comment] 2017-02-17 21:28
Good tip @tiesmaster Thanks very much.

By the way, you might want to try installing Paul Harrington's version.
https://marketplace.visualstudio.com/items?itemName=PaulHarrington.EditorGuidelines

**Comment by tiesmaster** [comment] 2017-02-17 22:01
I just did ;) I've been using that for years, but I was provisioning this new box, and noticed this from MS itself, so I thought, I'll give that a try. If I understand it correctly, all the Powertools features have been packaged as separate VSIXs, isn't it?

BTW I'm also looking for an extension that provides you with a couple missing features that ReSharper gives you. I know it's created by a Microsoft employee. Do you know by any chance which one that is? Among other things, it gives you "expand selection", any ideas?

**Comment by justcla** [comment] 2017-02-17 22:10
It sounds like you're referring to one of my extensions: Hot Commands

You can find the source code here: https://github.com/justcla/HotCommands
And it's available on the Marketplace here: http://aka.ms/HotCommands

If you're running without ReSharper, you might also want to take advantage of some alternative keyboard shortcuts: http://aka.ms/HotKeys

The Expand/Shrink selection feature is a little bit flaky at the moment; it sometimes selects too much.
I would love some help making it work nicely. Are you interested?

**Comment by justcla** [comment] 2017-02-17 22:19
And yes, we have separated all the PPT extensions.
I created a PPT installer that will install all extensions. ([Productivity Power Pack](https://marketplace.visualstudio.com/items?itemName=VisualStudioProductTeam.ProductivityPowerPack2017))

Many of the Power Tools were originally written by other people and we brought them in to PPT.
Paul Harrington wrote the original Editor Guidelines and seems to be doing a great job maintaining it, so we'll probably deprecate ours in favour of his.

**Comment by JVimes** [comment] 2017-02-17 22:45
@justcla Ah, thanks. It'd be nice to replace the current guidelines extension with Paul's, in the Power Pack.

**Comment by justcla** [comment] 2017-02-17 23:14
@JVimes Yep. That's the plan. ;-)

**Comment by tiesmaster** [comment] 2017-02-19 19:52
@justcla Amazing, I was actually looking for an extension by you, cool ;)

I'm definitely willing to help you improve it, I think it's really powerful, and also have a couple ideas for some things missing in the R# version, if you're interested. Though, I have a very busy period the next 2 months, so might not be able to help now.

**Comment by NKnusperer** [comment] 2017-03-08 10:30
Not fixed for the RTM?

**Comment by justcla** [comment] 2017-03-24 04:48
Fixed in [Editor Guidelines](https://marketplace.visualstudio.com/items?itemName=VisualStudioProductTeam.EditorGuidelines) version v15.0.1

**Closed** 2017-03-24 04:48 UTC
